"""PyGithub-based branch/commit/PR plumbing.

Fully implemented so the IaC hand-off path is real and reviewable, but only
exercised once real GITHUB_TOKEN / GITHUB_REPO_* settings are configured and
SUBMIT_REQUIREMENTS_MODE=full_pr is set.
"""

from github import Github, UnknownObjectException
from github.Auth import Token
from github.Repository import Repository

from app.config import Settings, get_settings


class GitHubClient:
    def __init__(self, settings: Settings | None = None) -> None:
        self.settings = settings or get_settings()
        if not self.settings.github_token:
            raise ValueError("GITHUB_TOKEN is not configured.")
        self._gh = Github(auth=Token(self.settings.github_token))

    def _repo(self) -> Repository:
        return self._gh.get_repo(f"{self.settings.github_repo_owner}/{self.settings.github_repo_name}")

    def create_feature_branch(self, repo: Repository, base_branch: str, new_branch: str) -> None:
        base_ref = repo.get_git_ref(f"heads/{base_branch}")
        repo.create_git_ref(ref=f"refs/heads/{new_branch}", sha=base_ref.object.sha)

    def commit_files(self, repo: Repository, branch: str, files: dict[str, str], message: str) -> None:
        for path, content in files.items():
            try:
                existing = repo.get_contents(path, ref=branch)
                repo.update_file(path, message, content, existing.sha, branch=branch)
            except UnknownObjectException:
                repo.create_file(path, message, content, branch=branch)

    def open_pull_request(self, repo: Repository, head: str, base: str, title: str, body: str):
        return repo.create_pull(title=title, body=body, head=head, base=base)

    def submit_infra_request(
        self, resource_type: str, slug: str, rendered_files: dict[str, str], requirements: dict
    ) -> dict:
        repo = self._repo()
        branch = f"{self.settings.github_pr_branch_prefix}{slug}"
        base = self.settings.github_base_branch

        self.create_feature_branch(repo, base, branch)

        commit_paths = {
            f"infra/{resource_type}/{slug}/{filename}": content
            for filename, content in rendered_files.items()
        }
        self.commit_files(repo, branch, commit_paths, message=f"Provision {resource_type}: {slug}")

        summary_rows = "\n".join(f"| {k} | {v} |" for k, v in sorted(requirements.items()))
        body = (
            f"Auto-generated by the Azure Infra Provisioning Agent.\n\n"
            f"### Requested configuration\n\n"
            f"| Field | Value |\n|---|---|\n{summary_rows}\n\n"
            f"Merging this PR triggers `terraform apply` via GitHub Actions."
        )
        pr = self.open_pull_request(
            repo, head=branch, base=base, title=f"Provision {resource_type}: {slug}", body=body
        )

        return {"pr_url": pr.html_url, "branch": branch, "files": list(commit_paths.keys())}
